#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
WORKER_ID="${WORKER_ID:-ubuntu-worker-01}"
WORKER_NAME="${WORKER_NAME:-ubuntu-atlas-01}"

FRONTEND_ROOT="${REPO_ROOT}/pilot_v1/customide/frontend"
ASSETS_ROOT="${FRONTEND_ROOT}/assets"
CSS_ROOT="${FRONTEND_ROOT}/css"
JS_ROOT="${FRONTEND_ROOT}/js"

cd "${REPO_ROOT}"

echo "task=MTASK-0038"
echo "worker_name=${WORKER_NAME}"
echo "worker_id=${WORKER_ID}"
echo "repo_root=${REPO_ROOT}"

git fetch origin
git pull --ff-only origin main

mkdir -p "${ASSETS_ROOT}" "${CSS_ROOT}" "${JS_ROOT}"

cat > "${FRONTEND_ROOT}/index.html" <<'HTML'
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>CustomIDE - Dual Pane</title>
  <link rel="stylesheet" href="css/style.css">
</head>
<body>
  <div class="bg-orbit"></div>
  <header class="topbar">
    <div class="brand">CustomIDE</div>
    <div class="status" id="backendStatus">Backend: checking...</div>
  </header>

  <main class="layout">
    <section class="pane pane-left">
      <div class="pane-title">Windows Editor</div>
      <textarea id="editor" spellcheck="false">// Start coding here...</textarea>
    </section>

    <section class="pane pane-right">
      <div class="pane-title">Worker 1 Remote View</div>
      <iframe id="remoteFrame" title="Worker 1 code-server view"></iframe>
      <div class="hint">Set remote URL in config when MTASK-0034 services are available.</div>
    </section>
  </main>

  <script src="js/app.js"></script>
</body>
</html>
HTML

cat > "${CSS_ROOT}/style.css" <<'CSS'
:root {
  --bg-a: #f3efe6;
  --bg-b: #d8e2dc;
  --ink: #22333b;
  --muted: #52616b;
  --line: #a8b8b3;
  --panel: rgba(255,255,255,0.7);
  --accent: #5a7d7c;
}

* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: Georgia, "Palatino Linotype", "Book Antiqua", serif;
  color: var(--ink);
  background: radial-gradient(circle at 20% 20%, var(--bg-b), var(--bg-a));
  min-height: 100vh;
}

.bg-orbit {
  position: fixed;
  inset: -20vmax;
  background: conic-gradient(from 120deg, transparent, rgba(90,125,124,0.15), transparent 55%);
  animation: drift 18s linear infinite;
  pointer-events: none;
}

@keyframes drift {
  to { transform: rotate(1turn); }
}

.topbar {
  position: sticky;
  top: 0;
  z-index: 2;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 14px 18px;
  border-bottom: 1px solid var(--line);
  background: rgba(243,239,230,0.86);
  backdrop-filter: blur(5px);
}

.brand {
  font-size: 1.25rem;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.status {
  color: var(--muted);
  font-size: 0.95rem;
}

.layout {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
  padding: 16px;
}

.pane {
  border: 1px solid var(--line);
  background: var(--panel);
  border-radius: 12px;
  overflow: hidden;
  min-height: calc(100vh - 96px);
  box-shadow: 0 10px 30px rgba(34,51,59,0.08);
}

.pane-title {
  padding: 10px 12px;
  border-bottom: 1px solid var(--line);
  font-weight: 600;
}

#editor {
  width: 100%;
  height: calc(100% - 42px);
  min-height: 60vh;
  border: 0;
  resize: none;
  padding: 14px;
  font-family: "Courier New", Courier, monospace;
  font-size: 14px;
  background: rgba(255,255,255,0.76);
}

#remoteFrame {
  width: 100%;
  height: calc(100% - 64px);
  min-height: 56vh;
  border: 0;
  background: #fff;
}

.hint {
  border-top: 1px solid var(--line);
  padding: 8px 10px;
  color: var(--muted);
  font-size: 0.85rem;
}

@media (max-width: 980px) {
  .layout { grid-template-columns: 1fr; }
  .pane { min-height: 46vh; }
}
CSS

cat > "${JS_ROOT}/app.js" <<'JS'
(async function main() {
  const statusEl = document.getElementById("backendStatus");
  const remoteFrame = document.getElementById("remoteFrame");

  try {
    const res = await fetch("http://127.0.0.1:5555/health");
    if (!res.ok) throw new Error("backend not healthy");
    const d = await res.json();
    statusEl.textContent = "Backend: " + (d.status || "unknown");
  } catch (_err) {
    statusEl.textContent = "Backend: offline (expected until local run)";
  }

  // Placeholder remote URL; MTASK-0039 wires real service config consumption.
  remoteFrame.src = "about:blank";
})();
JS

cat > "${FRONTEND_ROOT}/README.md" <<'MD'
# CustomIDE Frontend (Phase 4 Shell)

Generated by MTASK-0038.

## Purpose

Provides the first dual-pane shell:

- Left: local editor textarea
- Right: iframe placeholder for Worker 1 remote code-server

## Local run

Use any static server from `pilot_v1/customide/frontend`.

Example:

```bash
cd pilot_v1/customide/frontend
python3 -m http.server 5570
```

Open: http://127.0.0.1:5570
MD

echo "frontend_shell=created"
echo "frontend_root=${FRONTEND_ROOT}"

git add \
  "pilot_v1/customide/frontend/index.html" \
  "pilot_v1/customide/frontend/README.md" \
  "pilot_v1/customide/frontend/css/style.css" \
  "pilot_v1/customide/frontend/js/app.js"

git commit -m "customide: scaffold phase4 frontend shell (MTASK-0038)" || true
git push origin main || true

echo "timestamp_utc=$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
